### ISSUE TITLE
Many different books

### ISSUE THREAD

**Issue by Hajus** [pylgrym/roguelike#1]
There are at least three different books listed in online book stores, sometimes two at the same store. Which to get?

ISBN 9783757516765, 428 pages
ISBN 9788797439012, 458 pages
ISBN 9788797439029, 466 pages

**Comment by pylgrym** [comment]
They are all the same book, so pick the cheapest one (if you wish).
The reason they are different, is that each publisher wants an ISBN number
for publishing.
Also, different publishers support different sizes of books they will
print,
so whenever you pick a different publisher, you will often get different
sizes available.
  There should be no differences between the books.
The reason for multiples, is that different publishers serve different
areas/distribution networks,
offer different rates, and produce books of different levels of quality.
Some of the prints are more "hardback" like, some are more paperback-like.
Typically, the more expensive variant will be produced in a higher quality
(ie not paperbackish).
But given contents are the same, in the end it doesn't matter much.

As an example, the publisher that is the hardest to work with (from my
side),
is also the publisher with the most difficult publishing procedure
(the publisher IngramSpark). They can afford to be difficult, because
they are well aware they have the biggest worldwide distribution network;
I think they cover something like 70-90% of all internationally shipped
books
outside of US, and they are well aware of it.

That was probably more info than you wanted/needed,
but it's a dump of what I can remember off the top of my head.

Cheers, Jakob.

**Comment by pylgrym** [comment]
I failed to explain it plainly: the different book sizes offered by various
publishers, cause the same  identical contents to reflow to fill a
different number of pages. Simply that.

**Comment by Hajus** [comment]
Thank you for sharing your experience with self-publishing services. I understood the first time and did as you suggested and ordered the cheapest.
